name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      uses: actions/cache@v2
      env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('conda.yaml')}}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        channel-priority: strict
        environment-file: conda.yaml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Activate Conda
      run: |
        conda activate anaconda-client-env
    - name: MLFlow Training
      run: |
        mlflow run --experiment-name /Users/robert.bastian@enverus.com/mlflow-tensorflow-gha .
